local _, addonTable = ...

-- Dungeon/raid entrance database for PeaversGetThere. Fills the "only discovered
-- instances" gap in C_EncounterJournal.GetDungeonEntrancesForMap and anchors the
-- "dungeon:<journalInstanceID>" destinations used by the teleport catalog.
--
-- Schema (keyed by journalInstanceID):
--   [journalInstanceID] = {
--     map     = uiMapID of the entrance zone,
--     x, y    = normalized map coords (0-1),
--     name    = "enUS fallback name",  -- localized at runtime via EJ_GetInstanceInfo
--     kind    = "dungeon" | "raid",
--     faction = nil | "Alliance" | "Horde",
--   }
--
-- Empty until generated by getthere-module (PeaversAddonDataSupplier) from
-- wago.tools JournalInstance/JournalInstanceEntrance db2 exports. Do not hand-populate.
local data = {
	updated = "2026-07-16 00:00:00",

	entrances = {},
}

addonTable.DungeonEntrances = data
