local _, addonTable = ...

-- Curated seed data for the PeaversGetThere search index supplement: names and
-- aliases for POIs the client APIs cannot enumerate (services, portal rooms,
-- transport hubs). This file will be auto-generated by getthere-module
-- (PeaversAddonDataSupplier); until that pipeline ships it is hand-maintained.
--
-- Format follows the PeaversIconSearchData chunked-string blob pattern:
-- each chunk holds "payloadIndex:Display Name<TAB>search tags" lines, and
-- payloads[payloadIndex] carries the structured target:
--   { map = uiMapID, x = 0-1, y = 0-1, category = "service" | "travel",
--     nodeID = optional TravelNodes.lua key }
-- Consumers concatenate the chunks and scan them as one string (enUS only, v1).
--
-- TODO verify in-game: all coordinates in this file are best-effort approximations.
local payloads = {
	[1] = { map = 84, x = 0.610, y = 0.700, category = "service" },
	[2] = { map = 85, x = 0.540, y = 0.730, category = "service" },
	[3] = { map = 87, x = 0.255, y = 0.740, category = "service" },
	[4] = { map = 2112, x = 0.420, y = 0.420, category = "service" },
	[5] = { map = 2339, x = 0.550, y = 0.580, category = "service" },
	[6] = { map = 84, x = 0.492, y = 0.873, category = "travel" },
	[7] = { map = 85, x = 0.505, y = 0.890, category = "travel" },
	[8] = { map = 84, x = 0.612, y = 0.686, category = "service" },
	[9] = { map = 85, x = 0.555, y = 0.565, category = "service" },
	[10] = { map = 2112, x = 0.470, y = 0.600, category = "service" },
	[11] = { map = 2339, x = 0.520, y = 0.620, category = "service" },
	[12] = { map = 2112, x = 0.470, y = 0.350, category = "service" },
	[13] = { map = 2339, x = 0.435, y = 0.270, category = "service" },
	[14] = { map = 84, x = 0.633, y = 0.705, category = "service" },
	[15] = { map = 85, x = 0.500, y = 0.710, category = "service" },
	[16] = { map = 2112, x = 0.565, y = 0.535, category = "service" },
	[17] = { map = 2339, x = 0.530, y = 0.550, category = "service" },
	[18] = { map = 84, x = 0.660, y = 0.180, category = "travel", nodeID = "tram:stormwind" },
	[19] = { map = 87, x = 0.757, y = 0.512, category = "travel", nodeID = "tram:ironforge" },
	[20] = { map = 84, x = 0.225, y = 0.320, category = "travel", nodeID = "dock:stormwind-harbor" },
	[21] = { map = 85, x = 0.485, y = 0.585, category = "travel", nodeID = "zep:orgrimmar" },
	[22] = { map = 84, x = 0.545, y = 0.665, category = "service" },
	[23] = { map = 85, x = 0.440, y = 0.580, category = "service" },
}

local chunks = {}

chunks[#chunks + 1] = [==[
1:Auction House (Stormwind)	stormwind ah auction auctions gold sell
2:Auction House (Orgrimmar)	orgrimmar ah auction auctions gold sell
3:Auction House (Ironforge)	ironforge ah auction auctions gold sell
4:Auction House (Valdrakken)	valdrakken ah auction auctions gold sell
5:Auction House (Dornogal)	dornogal ah auction auctions gold sell
6:Portal Room (Stormwind)	stormwind wizards sanctum portals mage quarter
7:Portal Room (Orgrimmar)	orgrimmar pathfinders den portals
8:Barber Shop (Stormwind)	stormwind barber haircut appearance
9:Barber Shop (Orgrimmar)	orgrimmar barber haircut appearance
10:Barber Shop (Valdrakken)	valdrakken barber haircut appearance
11:Barber Shop (Dornogal)	dornogal barber haircut appearance
12:Great Vault (Valdrakken)	valdrakken weekly chest reward vault
13:Great Vault (Dornogal)	dornogal weekly chest reward vault
14:Bank (Stormwind)	stormwind bank vault gold
15:Bank (Orgrimmar)	orgrimmar bank vault gold
16:Bank (Valdrakken)	valdrakken bank vault gold
17:Bank (Dornogal)	dornogal bank vault gold
18:Deeprun Tram (Stormwind)	stormwind tram subway train ironforge
19:Deeprun Tram (Ironforge)	ironforge tram subway train stormwind
20:Stormwind Harbor	stormwind boat ship dock harbor
21:Orgrimmar Zeppelin Towers	orgrimmar zeppelin blimp tower
22:Trading Post (Stormwind)	stormwind tender monthly rewards trading
23:Trading Post (Orgrimmar)	orgrimmar tender monthly rewards trading
]==]

addonTable.SearchExtrasData = {
	updated = "2026-07-16 00:00:00",
	payloads = payloads,
	chunks = chunks,
}
