local _, addonTable = ...

-- Flight point database for PeaversGetThere. Provides taxi-node positions and
-- intra-continent edge hints so routing works before per-character discovery
-- data matters (C_TaxiMap only lists nodes per zone map at runtime).
--
-- Schema (keyed by TaxiNodes.db2 ID):
--   [taxiNodeID] = {
--     map     = uiMapID,
--     x, y    = normalized map coords (0-1),
--     name    = "enUS fallback name",  -- localized at runtime via C_TaxiMap where possible
--     faction = nil | "Alliance" | "Horde",
--     edges   = { [toTaxiNodeID] = seconds, ... },  -- flight-time hints
--   }
--
-- Empty until generated by getthere-module (PeaversAddonDataSupplier) from
-- wago.tools TaxiNodes/TaxiPath/TaxiPathNode db2 exports. Do not hand-populate.
local data = {
	updated = "2026-07-16 00:00:00",

	nodes = {},
}

addonTable.TaxiNodes = data
