local _, addonTable = ...

-- Curated seed data for the PeaversGetThere teleport catalog. This file will be
-- auto-generated by getthere-module (PeaversAddonDataSupplier) from wago.tools
-- db2 exports + curated seed JSON; until that pipeline ships it is hand-maintained.
--
-- Schema (see PeaversGetThere PLAN.md section 5.2), array of entries:
--   { id   = spellID | itemID,
--     type = "spell" | "item" | "toy",
--     dest = nodeID from TravelNodes.lua (omitted for hearthstones/menus),
--     hearthstone = true,          -- destination is the bound inn (resolved at runtime)
--     random = true,               -- random destination within `dest` region
--     menu = true,                 -- destination picker UI (e.g. Mole Machine)
--     class = "MAGE" | ..., race = "DarkIronDwarf" | ..., prof = "engineering",
--     faction = "Alliance" | "Horde",
--     req = { quest = {...}, ... },
--     journalInstanceID = n }      -- M+ dungeon teleports
--
-- Mage Portal: spells are intentionally omitted - for self-travel the Teleport:
-- variant is strictly better; group portals are out of scope for the catalog.
--
-- TODO verify in-game: spell/item IDs and type (item vs toy) flags below are
-- best-effort; the scraper run replaces this list wholesale.
local data = {
	updated = "2026-07-17 13:11:50",

	teleports = {
		-- ---------------------------------------------------------------
		-- Hearthstone and hearthstone-equivalents (bound-inn destination)
		-- ---------------------------------------------------------------
		{ id = 6948, type = "item", hearthstone = true }, -- Hearthstone
		{ id = 556, type = "spell", hearthstone = true, class = "SHAMAN" }, -- Astral Recall
		{ id = 54452, type = "toy", hearthstone = true }, -- Ethereal Portal
		{ id = 64488, type = "toy", hearthstone = true }, -- The Innkeeper's Daughter
		{ id = 93672, type = "toy", hearthstone = true }, -- Dark Portal
		{ id = 142542, type = "toy", hearthstone = true }, -- Tome of Town Portal
		{ id = 162973, type = "toy", hearthstone = true }, -- Greatfather Winter's Hearthstone
		{ id = 163045, type = "toy", hearthstone = true }, -- Headless Horseman's Hearthstone
		{ id = 165669, type = "toy", hearthstone = true }, -- Lunar Elder's Hearthstone
		{ id = 165670, type = "toy", hearthstone = true }, -- Peddlefeet's Lovely Hearthstone
		{ id = 165802, type = "toy", hearthstone = true }, -- Noble Gardener's Hearthstone
		{ id = 166746, type = "toy", hearthstone = true }, -- Fire Eater's Hearthstone
		{ id = 166747, type = "toy", hearthstone = true }, -- Brewfest Reveler's Hearthstone
		{ id = 168907, type = "toy", hearthstone = true }, -- Holographic Digitalization Hearthstone
		{ id = 172179, type = "toy", hearthstone = true }, -- Eternal Traveler's Hearthstone
		{ id = 180290, type = "toy", hearthstone = true }, -- Night Fae Hearthstone
		{ id = 182773, type = "toy", hearthstone = true }, -- Necrolord Hearthstone
		{ id = 183716, type = "toy", hearthstone = true }, -- Venthyr Sinstone
		{ id = 184353, type = "toy", hearthstone = true }, -- Kyrian Hearthstone
		{ id = 188952, type = "toy", hearthstone = true }, -- Dominated Hearthstone
		{ id = 190196, type = "toy", hearthstone = true }, -- Enlightened Hearthstone
		{ id = 190237, type = "toy", hearthstone = true }, -- Broker Translocation Matrix
		{ id = 193588, type = "toy", hearthstone = true }, -- Timewalker's Hearthstone
		{ id = 200630, type = "toy", hearthstone = true }, -- Ohn'ir Windsage's Hearthstone
		{ id = 206195, type = "toy", hearthstone = true }, -- Path of the Naaru
		{ id = 208704, type = "toy", hearthstone = true }, -- Deepdweller's Earthen Hearthstone
		{ id = 209035, type = "toy", hearthstone = true }, -- Hearthstone of the Flame
		{ id = 210455, type = "toy", hearthstone = true }, -- Draenic Hologem
		{ id = 212337, type = "toy", hearthstone = true }, -- Stone of the Hearth
		{ id = 228940, type = "toy", hearthstone = true }, -- Notorious Thread's Hearthstone

		-- ---------------------------------------------------------------
		-- Keyed hearthstones (fixed destination)
		-- ---------------------------------------------------------------
		{ id = 140192, type = "item", dest = "hub:dalaran-legion" }, -- Dalaran Hearthstone
		{ id = 110560, type = "item", dest = "hub:garrison", req = { quest = { 34378, 34586 } } }, -- Garrison Hearthstone

		-- ---------------------------------------------------------------
		-- Mage teleports
		-- ---------------------------------------------------------------
		{ id = 3561, type = "spell", dest = "hub:stormwind", class = "MAGE", faction = "Alliance" }, -- Teleport: Stormwind
		{ id = 3562, type = "spell", dest = "hub:ironforge", class = "MAGE", faction = "Alliance" }, -- Teleport: Ironforge
		{ id = 3565, type = "spell", dest = "hub:darnassus", class = "MAGE", faction = "Alliance" }, -- Teleport: Darnassus
		{ id = 32271, type = "spell", dest = "hub:exodar", class = "MAGE", faction = "Alliance" }, -- Teleport: Exodar
		{ id = 49359, type = "spell", dest = "dock:theramore", class = "MAGE", faction = "Alliance" }, -- Teleport: Theramore
		{ id = 33690, type = "spell", dest = "hub:shattrath", class = "MAGE", faction = "Alliance" }, -- Teleport: Shattrath (A)
		{ id = 132621, type = "spell", dest = "portal:vale:seven-stars", class = "MAGE", faction = "Alliance" }, -- Teleport: Vale of Eternal Blossoms (A)
		{ id = 176248, type = "spell", dest = "hub:stormshield", class = "MAGE", faction = "Alliance" }, -- Teleport: Stormshield
		{ id = 281403, type = "spell", dest = "hub:boralus", class = "MAGE", faction = "Alliance" }, -- Teleport: Boralus
		{ id = 3567, type = "spell", dest = "hub:orgrimmar", class = "MAGE", faction = "Horde" }, -- Teleport: Orgrimmar
		{ id = 3563, type = "spell", dest = "hub:undercity", class = "MAGE", faction = "Horde" }, -- Teleport: Undercity
		{ id = 3566, type = "spell", dest = "hub:thunderbluff", class = "MAGE", faction = "Horde" }, -- Teleport: Thunder Bluff
		{ id = 32272, type = "spell", dest = "hub:silvermoon", class = "MAGE", faction = "Horde" }, -- Teleport: Silvermoon
		{ id = 49358, type = "spell", dest = "poi:stonard", class = "MAGE", faction = "Horde" }, -- Teleport: Stonard
		{ id = 35715, type = "spell", dest = "hub:shattrath", class = "MAGE", faction = "Horde" }, -- Teleport: Shattrath (H)
		{ id = 132627, type = "spell", dest = "portal:vale:two-moons", class = "MAGE", faction = "Horde" }, -- Teleport: Vale of Eternal Blossoms (H)
		{ id = 176242, type = "spell", dest = "hub:warspear", class = "MAGE", faction = "Horde" }, -- Teleport: Warspear
		{ id = 281404, type = "spell", dest = "hub:dazaralor", class = "MAGE", faction = "Horde" }, -- Teleport: Dazar'alor
		{ id = 53140, type = "spell", dest = "hub:dalaran-northrend", class = "MAGE" }, -- Teleport: Dalaran - Northrend
		{ id = 224869, type = "spell", dest = "hub:dalaran-legion", class = "MAGE" }, -- Teleport: Dalaran - Broken Isles
		{ id = 344587, type = "spell", dest = "hub:oribos", class = "MAGE" }, -- Teleport: Oribos
		{ id = 395277, type = "spell", dest = "hub:valdrakken", class = "MAGE" }, -- Teleport: Valdrakken
		{ id = 446540, type = "spell", dest = "hub:dornogal", class = "MAGE" }, -- Teleport: Dornogal

		-- ---------------------------------------------------------------
		-- Other class teleports
		-- ---------------------------------------------------------------
		{ id = 50977, type = "spell", dest = "hub:acherus", class = "DEATHKNIGHT" }, -- Death Gate
		{ id = 193753, type = "spell", dest = "hub:emerald-dreamway", class = "DRUID" }, -- Dreamwalk
		{ id = 18960, type = "spell", dest = "hub:moonglade", class = "DRUID" }, -- Teleport: Moonglade
		{ id = 126892, type = "spell", dest = "hub:wandering-isle", class = "MONK" }, -- Zen Pilgrimage

		-- ---------------------------------------------------------------
		-- Racials
		-- ---------------------------------------------------------------
		{ id = 265225, type = "spell", race = "DarkIronDwarf", menu = true }, -- Mole Machine (destination picker)

		-- ---------------------------------------------------------------
		-- Engineering wormholes (random destination within region)
		-- ---------------------------------------------------------------
		{ id = 48933, type = "item", dest = "region:northrend", random = true, prof = "engineering" }, -- Wormhole Generator: Northrend
		{ id = 87215, type = "item", dest = "region:pandaria", random = true, prof = "engineering" }, -- Wormhole Generator: Pandaria
		{ id = 112059, type = "item", dest = "region:draenor", random = true, prof = "engineering" }, -- Wormhole Centrifuge
		{ id = 151652, type = "item", dest = "region:argus", random = true, prof = "engineering" }, -- Wormhole Generator: Argus
		{ id = 168807, type = "toy", dest = "region:kultiras", random = true, prof = "engineering" }, -- Wormhole Generator: Kul Tiras
		{ id = 168808, type = "toy", dest = "region:zandalar", random = true, prof = "engineering" }, -- Wormhole Generator: Zandalar
		{ id = 172924, type = "toy", dest = "region:shadowlands", random = true, prof = "engineering" }, -- Wormhole Generator: Shadowlands
		{ id = 198156, type = "toy", dest = "region:dragonisles", random = true, prof = "engineering" }, -- Wyrmhole Generator: Dragon Isles
		{ id = 221966, type = "toy", dest = "region:khazalgar", random = true, prof = "engineering" }, -- Wormhole Generator: Khaz Algar

		-- ---------------------------------------------------------------
		-- M+ dungeon teleports (The War Within era; earlier seasons and the
		-- current Midnight-season list come from the scraper).
		-- "dungeon:<journalInstanceID>" destinations resolve against
		-- DungeonEntrances.lua once the scraper populates it.
		-- ---------------------------------------------------------------
		{ id = 445417, type = "spell", dest = "dungeon:1271", journalInstanceID = 1271 }, -- Path of the Ara-Kara, City of Echoes
		{ id = 445416, type = "spell", dest = "dungeon:1274", journalInstanceID = 1274 }, -- Path of the City of Threads
		{ id = 445414, type = "spell", dest = "dungeon:1270", journalInstanceID = 1270 }, -- Path of the Dawnbreaker
		{ id = 445269, type = "spell", dest = "dungeon:1269", journalInstanceID = 1269 }, -- Path of the Stonevault
		{ id = 445443, type = "spell", dest = "dungeon:1268", journalInstanceID = 1268 }, -- Path of the Rookery
		{ id = 445444, type = "spell", dest = "dungeon:1267", journalInstanceID = 1267 }, -- Path of the Sacred Flame
		{ id = 445441, type = "spell", dest = "dungeon:1210", journalInstanceID = 1210 }, -- Path of the Darkflame Cleft
		{ id = 445440, type = "spell", dest = "dungeon:1272", journalInstanceID = 1272 }, -- Path of the Cinderbrew Meadery
	},
}

addonTable.Teleports = data
