local _, addonTable = ...

-- Curated seed data for the PeaversGetThere travel graph. This file will be
-- auto-generated by getthere-module (PeaversAddonDataSupplier) from wago.tools
-- db2 exports + curated seed JSON; until that pipeline ships it is hand-maintained.
--
-- Schema (see PeaversGetThere PLAN.md section 5.1), array of edges:
--   { from = nodeID, to = nodeID,
--     method = "portal" | "boat" | "zeppelin" | "tram" | "taxi" | "walkhint",
--     cost   = seconds,           -- fixed for transports (incl. avg wait + loading screen)
--     req    = ... }              -- same requirement shape as nodes
--
-- Faction gating lives on the endpoint nodes (see TravelNodes.lua); walk/fly,
-- teleport and taxi edges are injected at runtime and never shipped here.
--
-- TODO verify in-game: costs are best-effort estimates (portal ~15 s incl. loading
-- screen, tram ~150 s, boats/zeppelins ~240 s incl. average wait).
local data = {
	updated = "2026-07-17 13:11:50",

	edges = {
		-- Stormwind Portal Room (Wizard's Sanctum)
		{ from = "portal:stormwind:valdrakken", to = "hub:valdrakken", method = "portal", cost = 15 },
		{ from = "portal:stormwind:dornogal", to = "hub:dornogal", method = "portal", cost = 15 },
		{ from = "portal:stormwind:oribos", to = "hub:oribos", method = "portal", cost = 15 },
		{ from = "portal:stormwind:boralus", to = "hub:boralus", method = "portal", cost = 15 },
		{ from = "portal:stormwind:azsuna", to = "portal:azsuna:meredil", method = "portal", cost = 15 },
		{ from = "portal:stormwind:jade-forest", to = "portal:jade-forest:pawdon", method = "portal", cost = 15 },
		{ from = "portal:stormwind:uldum", to = "portal:uldum:ramkahen", method = "portal", cost = 15 },
		{ from = "portal:stormwind:vale", to = "portal:vale:seven-stars", method = "portal", cost = 15 },
		{ from = "portal:stormwind:shattrath", to = "hub:shattrath", method = "portal", cost = 15 },
		{ from = "portal:stormwind:exodar", to = "hub:exodar", method = "portal", cost = 15 },
		{ from = "portal:stormwind:stormshield", to = "hub:stormshield", method = "portal", cost = 15 },
		{ from = "portal:stormwind:silvermoon", to = "hub:silvermoon", method = "portal", cost = 15 },

		-- Orgrimmar Portal Room (Pathfinder's Den)
		{ from = "portal:orgrimmar:valdrakken", to = "hub:valdrakken", method = "portal", cost = 15 },
		{ from = "portal:orgrimmar:dornogal", to = "hub:dornogal", method = "portal", cost = 15 },
		{ from = "portal:orgrimmar:oribos", to = "hub:oribos", method = "portal", cost = 15 },
		{ from = "portal:orgrimmar:dazaralor", to = "hub:dazaralor", method = "portal", cost = 15 },
		{ from = "portal:orgrimmar:azsuna", to = "portal:azsuna:meredil", method = "portal", cost = 15 },
		{ from = "portal:orgrimmar:jade-forest", to = "portal:jade-forest:honeydew", method = "portal", cost = 15 },
		{ from = "portal:orgrimmar:uldum", to = "portal:uldum:ramkahen", method = "portal", cost = 15 },
		{ from = "portal:orgrimmar:vale", to = "portal:vale:two-moons", method = "portal", cost = 15 },
		{ from = "portal:orgrimmar:shattrath", to = "hub:shattrath", method = "portal", cost = 15 },
		{ from = "portal:orgrimmar:silvermoon", to = "hub:silvermoon", method = "portal", cost = 15 },
		{ from = "portal:orgrimmar:warspear", to = "hub:warspear", method = "portal", cost = 15 },

		-- Return portals to the capitals
		{ from = "portal:valdrakken:stormwind", to = "hub:stormwind", method = "portal", cost = 15 },
		{ from = "portal:valdrakken:orgrimmar", to = "hub:orgrimmar", method = "portal", cost = 15 },
		{ from = "portal:dornogal:stormwind", to = "hub:stormwind", method = "portal", cost = 15 },
		{ from = "portal:dornogal:orgrimmar", to = "hub:orgrimmar", method = "portal", cost = 15 },
		{ from = "portal:silvermoon:stormwind", to = "hub:stormwind", method = "portal", cost = 15 },
		{ from = "portal:silvermoon:orgrimmar", to = "hub:orgrimmar", method = "portal", cost = 15 },
		{ from = "portal:oribos:stormwind", to = "hub:stormwind", method = "portal", cost = 15 },
		{ from = "portal:oribos:orgrimmar", to = "hub:orgrimmar", method = "portal", cost = 15 },
		{ from = "portal:boralus:stormwind", to = "hub:stormwind", method = "portal", cost = 15 },
		{ from = "portal:dazaralor:orgrimmar", to = "hub:orgrimmar", method = "portal", cost = 15 },
		{ from = "portal:dalaran-legion:stormwind", to = "hub:stormwind", method = "portal", cost = 15 },
		{ from = "portal:dalaran-legion:orgrimmar", to = "hub:orgrimmar", method = "portal", cost = 15 },
		{ from = "portal:dalaran-northrend:stormwind", to = "hub:stormwind", method = "portal", cost = 15 },
		{ from = "portal:dalaran-northrend:orgrimmar", to = "hub:orgrimmar", method = "portal", cost = 15 },

		-- Walk hints (cross-uiMap links runtime walk edges cannot infer:
		-- Oribos' portal floor, the Ring of Transference, is uiMap 1671
		-- while the hub anchor sits on the Ring of Fates, uiMap 1670)
		{ from = "hub:oribos", to = "portal:oribos:stormwind", method = "walkhint", cost = 45 },
		{ from = "hub:oribos", to = "portal:oribos:orgrimmar", method = "walkhint", cost = 45 },

		-- Deeprun Tram
		{ from = "tram:stormwind", to = "tram:ironforge", method = "tram", cost = 150 },
		{ from = "tram:ironforge", to = "tram:stormwind", method = "tram", cost = 150 },

		-- Boats
		{ from = "dock:stormwind-harbor", to = "dock:boralus", method = "boat", cost = 240 },
		{ from = "dock:boralus", to = "dock:stormwind-harbor", method = "boat", cost = 240 },
		{ from = "dock:stormwind-harbor", to = "dock:rutheran", method = "boat", cost = 240 },
		{ from = "dock:rutheran", to = "dock:stormwind-harbor", method = "boat", cost = 240 },
		{ from = "dock:stormwind-harbor", to = "dock:valiance-keep", method = "boat", cost = 240 },
		{ from = "dock:valiance-keep", to = "dock:stormwind-harbor", method = "boat", cost = 240 },
		{ from = "dock:menethil", to = "dock:theramore", method = "boat", cost = 240 },
		{ from = "dock:theramore", to = "dock:menethil", method = "boat", cost = 240 },
		{ from = "dock:menethil", to = "dock:valgarde", method = "boat", cost = 240 },
		{ from = "dock:valgarde", to = "dock:menethil", method = "boat", cost = 240 },
		{ from = "dock:ratchet", to = "dock:booty-bay", method = "boat", cost = 240 },
		{ from = "dock:booty-bay", to = "dock:ratchet", method = "boat", cost = 240 },
		{ from = "dock:bladefist-bay", to = "dock:dazaralor-port", method = "boat", cost = 240 },
		{ from = "dock:dazaralor-port", to = "dock:bladefist-bay", method = "boat", cost = 240 },

		-- Zeppelins
		{ from = "zep:orgrimmar", to = "zep:brill", method = "zeppelin", cost = 240 },
		{ from = "zep:brill", to = "zep:orgrimmar", method = "zeppelin", cost = 240 },
		{ from = "zep:orgrimmar", to = "zep:gromgol", method = "zeppelin", cost = 240 },
		{ from = "zep:gromgol", to = "zep:orgrimmar", method = "zeppelin", cost = 240 },
		{ from = "zep:orgrimmar", to = "zep:thunderbluff", method = "zeppelin", cost = 240 },
		{ from = "zep:thunderbluff", to = "zep:orgrimmar", method = "zeppelin", cost = 240 },
		{ from = "zep:orgrimmar", to = "zep:warsong-hold", method = "zeppelin", cost = 240 },
		{ from = "zep:warsong-hold", to = "zep:orgrimmar", method = "zeppelin", cost = 240 },
		{ from = "zep:brill", to = "zep:gromgol", method = "zeppelin", cost = 240 },
		{ from = "zep:gromgol", to = "zep:brill", method = "zeppelin", cost = 240 },
	},
}

addonTable.TravelEdges = data
