local _, addonTable = ...

-- Curated seed data for the PeaversGetThere travel graph. This file will be
-- auto-generated by getthere-module (PeaversAddonDataSupplier) from wago.tools
-- db2 exports + curated seed JSON; until that pipeline ships it is hand-maintained.
--
-- Schema (see PeaversGetThere PLAN.md section 5.1), keyed by stable string nodeID:
--   [nodeID] = {
--     kind    = "portal_src" | "portal_dst" | "dock" | "tram" | "taxi" | "hub" | "region" | "poi",
--               ("region" = destination anchor for random-destination teleports,
--                e.g. engineering wormholes - not a searchable place; consumers
--                should skip this kind when building the location index)
--     map     = uiMapID,
--     x, y    = normalized map coords (0-1),
--     name    = "enUS fallback name",   -- resolve localized where an ID exists
--     faction = nil | "Alliance" | "Horde",
--     req     = nil | { quest = {...}, level = n, prof = "engineering", class = "MAGE", ... },
--   }
--
-- TODO verify in-game: all coordinates in this file are best-effort approximations
-- and portal-room contents should be re-checked against the live client.
local data = {
	updated = "2026-07-17 13:11:50",

	nodes = {
		-- ---------------------------------------------------------------
		-- Hub anchors (cities and arrival points teleports resolve to)
		-- ---------------------------------------------------------------
		["hub:stormwind"] = { kind = "hub", map = 84, x = 0.615, y = 0.720, name = "Stormwind City", faction = "Alliance" },
		["hub:ironforge"] = { kind = "hub", map = 87, x = 0.455, y = 0.490, name = "Ironforge", faction = "Alliance" },
		["hub:darnassus"] = { kind = "hub", map = 89, x = 0.440, y = 0.530, name = "Darnassus", faction = "Alliance" },
		["hub:exodar"] = { kind = "hub", map = 103, x = 0.540, y = 0.440, name = "The Exodar", faction = "Alliance" },
		["hub:orgrimmar"] = { kind = "hub", map = 85, x = 0.520, y = 0.620, name = "Orgrimmar", faction = "Horde" },
		["hub:thunderbluff"] = { kind = "hub", map = 88, x = 0.470, y = 0.510, name = "Thunder Bluff", faction = "Horde" },
		["hub:undercity"] = { kind = "hub", map = 90, x = 0.560, y = 0.550, name = "Undercity", faction = "Horde" }, -- mage teleport target; city access gated since BfA
		["hub:silvermoon"] = { kind = "hub", map = 2393, x = 0.510, y = 0.710, name = "Silvermoon City" }, -- Midnight relocated Silvermoon to uiMap 2393; anchored to scraped taxi node 3131 Sanctum of Light (neutral). Was uiMap 110 (pre-Midnight Silvermoon).
		["hub:shattrath"] = { kind = "hub", map = 111, x = 0.530, y = 0.440, name = "Shattrath City" },
		["hub:dalaran-northrend"] = { kind = "hub", map = 125, x = 0.500, y = 0.500, name = "Dalaran (Northrend)" },
		["hub:dalaran-legion"] = { kind = "hub", map = 627, x = 0.500, y = 0.500, name = "Dalaran (Broken Isles)" },
		["hub:stormshield"] = { kind = "hub", map = 622, x = 0.510, y = 0.530, name = "Stormshield", faction = "Alliance" },
		["hub:warspear"] = { kind = "hub", map = 624, x = 0.510, y = 0.500, name = "Warspear", faction = "Horde" },
		["hub:boralus"] = { kind = "hub", map = 1161, x = 0.700, y = 0.250, name = "Boralus", faction = "Alliance" },
		["hub:dazaralor"] = { kind = "hub", map = 1165, x = 0.510, y = 0.470, name = "Dazar'alor", faction = "Horde" },
		["hub:oribos"] = { kind = "hub", map = 1670, x = 0.500, y = 0.550, name = "Oribos" },
		["hub:valdrakken"] = { kind = "hub", map = 2112, x = 0.560, y = 0.560, name = "Valdrakken" },
		["hub:dornogal"] = { kind = "hub", map = 2339, x = 0.470, y = 0.520, name = "Dornogal" },
		["hub:garrison"] = { kind = "hub", map = 582, x = 0.500, y = 0.500, name = "Lunarfall", faction = "Alliance" }, -- Garrison Hearthstone dest; consumer faction-switches to hub:garrison-horde for Horde
		["hub:garrison-horde"] = { kind = "hub", map = 590, x = 0.500, y = 0.500, name = "Frostwall", faction = "Horde" }, -- Horde counterpart of hub:garrison (not referenced by Teleports.lua; mapped at runtime)
		["hub:acherus"] = { kind = "hub", map = 648, x = 0.500, y = 0.500, name = "Acherus: The Ebon Hold", req = { class = "DEATHKNIGHT" } },
		["hub:moonglade"] = { kind = "hub", map = 80, x = 0.520, y = 0.410, name = "Moonglade" },
		["hub:emerald-dreamway"] = { kind = "hub", map = 715, x = 0.500, y = 0.500, name = "The Emerald Dreamway", req = { class = "DRUID" } },
		["hub:wandering-isle"] = { kind = "hub", map = 709, x = 0.500, y = 0.500, name = "The Wandering Isle", req = { class = "MONK" } },

		-- ---------------------------------------------------------------
		-- Region anchors (random-destination teleports, e.g. wormholes)
		-- ---------------------------------------------------------------
		["region:northrend"] = { kind = "region", map = 113, x = 0.500, y = 0.500, name = "Northrend" },
		["region:pandaria"] = { kind = "region", map = 424, x = 0.500, y = 0.500, name = "Pandaria" },
		["region:draenor"] = { kind = "region", map = 572, x = 0.500, y = 0.500, name = "Draenor" },
		["region:argus"] = { kind = "region", map = 905, x = 0.500, y = 0.500, name = "Argus" },
		["region:kultiras"] = { kind = "region", map = 876, x = 0.500, y = 0.500, name = "Kul Tiras" },
		["region:zandalar"] = { kind = "region", map = 875, x = 0.500, y = 0.500, name = "Zandalar" },
		["region:shadowlands"] = { kind = "region", map = 1550, x = 0.500, y = 0.500, name = "The Shadowlands" },
		["region:dragonisles"] = { kind = "region", map = 1978, x = 0.500, y = 0.500, name = "The Dragon Isles" },
		["region:khazalgar"] = { kind = "region", map = 2274, x = 0.500, y = 0.500, name = "Khaz Algar" },

		-- ---------------------------------------------------------------
		-- Stormwind Portal Room (Wizard's Sanctum, Mage Quarter)
		-- ---------------------------------------------------------------
		["portal:stormwind:valdrakken"] = { kind = "portal_src", map = 84, x = 0.492, y = 0.873, name = "Portal to Valdrakken", faction = "Alliance" },
		["portal:stormwind:dornogal"] = { kind = "portal_src", map = 84, x = 0.492, y = 0.873, name = "Portal to Dornogal", faction = "Alliance" },
		["portal:stormwind:oribos"] = { kind = "portal_src", map = 84, x = 0.492, y = 0.873, name = "Portal to Oribos", faction = "Alliance" },
		["portal:stormwind:boralus"] = { kind = "portal_src", map = 84, x = 0.492, y = 0.873, name = "Portal to Boralus", faction = "Alliance" },
		["portal:stormwind:azsuna"] = { kind = "portal_src", map = 84, x = 0.492, y = 0.873, name = "Portal to Azsuna", faction = "Alliance" },
		["portal:stormwind:jade-forest"] = { kind = "portal_src", map = 84, x = 0.492, y = 0.873, name = "Portal to Paw'don Grove", faction = "Alliance" },
		["portal:stormwind:uldum"] = { kind = "portal_src", map = 84, x = 0.492, y = 0.873, name = "Portal to Uldum", faction = "Alliance" },
		["portal:stormwind:vale"] = { kind = "portal_src", map = 84, x = 0.492, y = 0.873, name = "Portal to the Vale of Eternal Blossoms", faction = "Alliance" },
		["portal:stormwind:shattrath"] = { kind = "portal_src", map = 84, x = 0.492, y = 0.873, name = "Portal to Shattrath", faction = "Alliance" },
		["portal:stormwind:exodar"] = { kind = "portal_src", map = 84, x = 0.492, y = 0.873, name = "Portal to the Exodar", faction = "Alliance" },
		["portal:stormwind:stormshield"] = { kind = "portal_src", map = 84, x = 0.492, y = 0.873, name = "Portal to Stormshield", faction = "Alliance" },
		["portal:stormwind:silvermoon"] = { kind = "portal_src", map = 84, x = 0.492, y = 0.873, name = "Portal to Silvermoon", faction = "Alliance" },

		-- ---------------------------------------------------------------
		-- Orgrimmar Portal Room (Pathfinder's Den, Valley of Strength)
		-- ---------------------------------------------------------------
		["portal:orgrimmar:valdrakken"] = { kind = "portal_src", map = 85, x = 0.505, y = 0.890, name = "Portal to Valdrakken", faction = "Horde" },
		["portal:orgrimmar:dornogal"] = { kind = "portal_src", map = 85, x = 0.505, y = 0.890, name = "Portal to Dornogal", faction = "Horde" },
		["portal:orgrimmar:oribos"] = { kind = "portal_src", map = 85, x = 0.505, y = 0.890, name = "Portal to Oribos", faction = "Horde" },
		["portal:orgrimmar:dazaralor"] = { kind = "portal_src", map = 85, x = 0.505, y = 0.890, name = "Portal to Dazar'alor", faction = "Horde" },
		["portal:orgrimmar:azsuna"] = { kind = "portal_src", map = 85, x = 0.505, y = 0.890, name = "Portal to Azsuna", faction = "Horde" },
		["portal:orgrimmar:jade-forest"] = { kind = "portal_src", map = 85, x = 0.505, y = 0.890, name = "Portal to Honeydew Village", faction = "Horde" },
		["portal:orgrimmar:uldum"] = { kind = "portal_src", map = 85, x = 0.505, y = 0.890, name = "Portal to Uldum", faction = "Horde" },
		["portal:orgrimmar:vale"] = { kind = "portal_src", map = 85, x = 0.505, y = 0.890, name = "Portal to the Vale of Eternal Blossoms", faction = "Horde" },
		["portal:orgrimmar:shattrath"] = { kind = "portal_src", map = 85, x = 0.505, y = 0.890, name = "Portal to Shattrath", faction = "Horde" },
		["portal:orgrimmar:silvermoon"] = { kind = "portal_src", map = 85, x = 0.505, y = 0.890, name = "Portal to Silvermoon", faction = "Horde" },
		["portal:orgrimmar:warspear"] = { kind = "portal_src", map = 85, x = 0.505, y = 0.890, name = "Portal to Warspear", faction = "Horde" },

		-- ---------------------------------------------------------------
		-- Portal arrival points (zone drops that are not hub anchors)
		-- ---------------------------------------------------------------
		["portal:azsuna:meredil"] = { kind = "portal_dst", map = 630, x = 0.467, y = 0.410, name = "Meredil" },
		["portal:jade-forest:pawdon"] = { kind = "portal_dst", map = 371, x = 0.460, y = 0.850, name = "Paw'don Grove", faction = "Alliance" },
		["portal:jade-forest:honeydew"] = { kind = "portal_dst", map = 371, x = 0.285, y = 0.140, name = "Honeydew Village", faction = "Horde" },
		["portal:uldum:ramkahen"] = { kind = "portal_dst", map = 249, x = 0.545, y = 0.330, name = "Ramkahen" },
		["portal:vale:seven-stars"] = { kind = "portal_dst", map = 390, x = 0.840, y = 0.600, name = "Shrine of Seven Stars", faction = "Alliance" },
		["portal:vale:two-moons"] = { kind = "portal_dst", map = 390, x = 0.620, y = 0.220, name = "Shrine of Two Moons", faction = "Horde" },

		-- ---------------------------------------------------------------
		-- Return portals to the capitals
		-- ---------------------------------------------------------------
		["portal:valdrakken:stormwind"] = { kind = "portal_src", map = 2112, x = 0.595, y = 0.440, name = "Valdrakken Portal to Stormwind", faction = "Alliance" },
		["portal:valdrakken:orgrimmar"] = { kind = "portal_src", map = 2112, x = 0.610, y = 0.460, name = "Valdrakken Portal to Orgrimmar", faction = "Horde" },
		["portal:dornogal:stormwind"] = { kind = "portal_src", map = 2339, x = 0.550, y = 0.480, name = "Dornogal Portal to Stormwind", faction = "Alliance" },
		["portal:dornogal:orgrimmar"] = { kind = "portal_src", map = 2339, x = 0.570, y = 0.500, name = "Dornogal Portal to Orgrimmar", faction = "Horde" },
		["portal:silvermoon:stormwind"] = { kind = "portal_src", map = 2393, x = 0.526, y = 0.645, name = "Silvermoon Portal to Stormwind", faction = "Alliance" }, -- Midnight Silvermoon portal room; coords measured in-game
		["portal:silvermoon:orgrimmar"] = { kind = "portal_src", map = 2393, x = 0.526, y = 0.645, name = "Silvermoon Portal to Orgrimmar", faction = "Horde" }, -- Midnight Silvermoon portal room; coords approximated to the adjacent Alliance portal (only that one was measured)
		["portal:oribos:stormwind"] = { kind = "portal_src", map = 1671, x = 0.240, y = 0.500, name = "Oribos Portal to Stormwind", faction = "Alliance" }, -- Ring of Transference
		["portal:oribos:orgrimmar"] = { kind = "portal_src", map = 1671, x = 0.760, y = 0.500, name = "Oribos Portal to Orgrimmar", faction = "Horde" }, -- Ring of Transference
		["portal:boralus:stormwind"] = { kind = "portal_src", map = 1161, x = 0.707, y = 0.172, name = "Sanctum of the Sages Portal to Stormwind", faction = "Alliance" },
		["portal:dazaralor:orgrimmar"] = { kind = "portal_src", map = 1165, x = 0.517, y = 0.470, name = "Great Seal Portal to Orgrimmar", faction = "Horde" },
		["portal:dalaran-legion:stormwind"] = { kind = "portal_src", map = 627, x = 0.395, y = 0.630, name = "Greyfang Enclave Portal to Stormwind", faction = "Alliance" },
		["portal:dalaran-legion:orgrimmar"] = { kind = "portal_src", map = 627, x = 0.554, y = 0.240, name = "Windrunner's Sanctuary Portal to Orgrimmar", faction = "Horde" },
		["portal:dalaran-northrend:stormwind"] = { kind = "portal_src", map = 125, x = 0.370, y = 0.630, name = "Silver Enclave Portal to Stormwind", faction = "Alliance" },
		["portal:dalaran-northrend:orgrimmar"] = { kind = "portal_src", map = 125, x = 0.560, y = 0.220, name = "Sunreaver's Sanctuary Portal to Orgrimmar", faction = "Horde" },

		-- ---------------------------------------------------------------
		-- Deeprun Tram
		-- ---------------------------------------------------------------
		["tram:stormwind"] = { kind = "tram", map = 84, x = 0.660, y = 0.180, name = "Deeprun Tram (Stormwind)", faction = "Alliance" },
		["tram:ironforge"] = { kind = "tram", map = 87, x = 0.757, y = 0.512, name = "Deeprun Tram (Ironforge)", faction = "Alliance" },

		-- ---------------------------------------------------------------
		-- Boat docks
		-- ---------------------------------------------------------------
		["dock:stormwind-harbor"] = { kind = "dock", map = 84, x = 0.225, y = 0.320, name = "Stormwind Harbor", faction = "Alliance" },
		["dock:boralus"] = { kind = "dock", map = 1161, x = 0.727, y = 0.253, name = "Boralus Harbor", faction = "Alliance" },
		["dock:rutheran"] = { kind = "dock", map = 57, x = 0.550, y = 0.900, name = "Rut'theran Village", faction = "Alliance" },
		["dock:valiance-keep"] = { kind = "dock", map = 114, x = 0.595, y = 0.685, name = "Valiance Keep", faction = "Alliance" },
		["dock:menethil"] = { kind = "dock", map = 56, x = 0.095, y = 0.595, name = "Menethil Harbor", faction = "Alliance" },
		["dock:theramore"] = { kind = "dock", map = 70, x = 0.715, y = 0.565, name = "Theramore Isle" },
		["dock:valgarde"] = { kind = "dock", map = 117, x = 0.605, y = 0.620, name = "Valgarde", faction = "Alliance" },
		["dock:ratchet"] = { kind = "dock", map = 10, x = 0.680, y = 0.720, name = "Ratchet" },
		["dock:booty-bay"] = { kind = "dock", map = 210, x = 0.270, y = 0.730, name = "Booty Bay" },
		["dock:bladefist-bay"] = { kind = "dock", map = 1, x = 0.575, y = 0.110, name = "Bladefist Bay", faction = "Horde" }, -- Durotar
		["dock:dazaralor-port"] = { kind = "dock", map = 1165, x = 0.510, y = 0.930, name = "Port of Zandalar", faction = "Horde" },

		-- ---------------------------------------------------------------
		-- Zeppelin towers
		-- ---------------------------------------------------------------
		["zep:orgrimmar"] = { kind = "dock", map = 85, x = 0.485, y = 0.585, name = "Orgrimmar Zeppelin Towers", faction = "Horde" },
		["zep:brill"] = { kind = "dock", map = 18, x = 0.606, y = 0.588, name = "Brill Zeppelin Tower", faction = "Horde" }, -- Tirisfal Glades
		["zep:thunderbluff"] = { kind = "dock", map = 88, x = 0.470, y = 0.500, name = "Thunder Bluff Zeppelin Tower", faction = "Horde" },
		["zep:gromgol"] = { kind = "dock", map = 50, x = 0.375, y = 0.510, name = "Grom'gol Base Camp", faction = "Horde" }, -- Northern Stranglethorn
		["zep:warsong-hold"] = { kind = "dock", map = 114, x = 0.410, y = 0.545, name = "Warsong Hold Zeppelin Tower", faction = "Horde" }, -- Borean Tundra

		-- ---------------------------------------------------------------
		-- Misc POIs referenced by the teleport catalog
		-- ---------------------------------------------------------------
		["poi:stonard"] = { kind = "poi", map = 51, x = 0.465, y = 0.545, name = "Stonard", faction = "Horde" }, -- Swamp of Sorrows
	},
}

addonTable.TravelNodes = data
